### PR TITLE
Updated NAN

### PR DESCRIPTION
**Pull request by CJNE**
Enable build on newer node versions

### CODE REVIEW

**Comment by alexkirsz** [comment]
Updated and published 👍

Would you be interested in becoming a maintainer of this repo with publish rights on npm?

**Comment by CJNE** [comment]
Hello, thanks for the quick merge!
Yes it would be convenient to be able to keep it up to date myself so i’d
be happy to become a maintainer :)

Regards
Johan Isaksson

ons 6 dec. 2017 kl. 12:14 skrev Alexandre Kirszenberg <
notifications@github.com>:

**Comment by alexkirsz** [comment]
I added you as a collaborator both on here and on NPM :)

Thanks for keeping this package up to date!

**Comment by CJNE** [comment]
Great, i'll do my best to keep it up to date :)
Thank you for creating it in the first place!

Regards
Johan

mån 11 dec. 2017 kl 23:22 skrev Alexandre Kirszenberg <
notifications@github.com>:

**Pull request merged**
